13:35:06 - app.py:68 - INFO: Server started ('200.1.1.135', 8888)
13:35:06 - app.py:69 - INFO: Connect to ('200.1.1.135', 8888) to get the content of ('10.83.42.198', 22)
13:35:15 - app.py:72 - INFO: [Establishing] ('200.1.1.115', 51916) -> ('200.1.1.135', 8888) -> ? -> ('10.83.42.198', 22)
13:35:15 - app.py:76 - INFO: [OK] ('200.1.1.115', 51916) -> ('200.1.1.135', 8888) -> ('10.83.41.66', 3782) -> ('10.83.42.198', 22)
13:35:27 - app.py:55 - ERROR: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)
13:35:27 - app.py:57 - WARNING: Closing connect ('200.1.1.135', 8888)! 
13:35:27 - app.py:59 - WARNING: Closing connect ('10.83.41.66', 3782)! 
13:35:27 - app.py:55 - ERROR: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)
13:35:27 - app.py:57 - WARNING: Closing connect ('10.83.41.66', 3782)! 
13:35:27 - app.py:59 - WARNING: Closing connect ('200.1.1.135', 8888)! 
